### ISSUE TITLE
Wrong placement of new windows in a dualhead setup

### ISSUE THREAD

**Issue by okraits** [pekwm/pekwm#143]
How to reproduce:

1. I'm using a dualhead setup.
2. I have this in my configuration: `CurrHeadSelector = "FocusedWindow"`
3. Both focused window and mouse cursor are on head 2.
4. On head 2 there is no space left for a new terminal window, on head 1 there is space left.
5. If I spawn a new terminal window, it appears on head 1.

**Comment by pekdon** [comment]
This is actually by design, the current head will be the one first tried (unless it has fullscreen window) and if placement fails on that pekwm will try to find space on another head.

What does your **Screen/PlacementModel** say? If it has a Centered or MouseTopLeft at the end placement should not fail and the window should stay on the active head unless there's a fullscreen window.

As for the avoiding fullscreen windows, that's to not get new windows hidden so not sure if it's a good idea to make it configurable and possible to disable.

**Comment by okraits** [comment]
> What does your **Screen/PlacementModel** say? If it has a Centered or MouseTopLeft at the end placement should not fail and the window should stay on the active head unless there's a fullscreen window.

I only have `Smart` in the list of models. So when I'm back at the dualhead setup I will add one of those two you suggested to the list and see if that fixes the issue.

**Comment by okraits** [comment]
I modified my **Screen/Placement/Model** setting to have the value _Smart Centered_. In the situation described above, new windows are now placed centered on the head with the focused window, how it should be.

@pekdon Thank you!
